=== clescot/jguard/jguard-ext/src/test/resources/jGuardFilter_2.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://jguard.sourceforge.net/xsd/jGuardFilter_2.0.0.xsd"
            xmlns:tns="http://jguard.sourceforge.net/xsd/jGuardFilter_2.0.0.xsd"
            elementFormDefault="qualified">
    <xsd:complexType name="parameter">
        <xsd:attribute name="key" type="xsd:string"/>
        <xsd:attribute name="value" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="authenticationSchemeHandler">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="parameter" type="tns:parameter" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="className" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="callbackHandler">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="authenticationSchemeHandler" type="tns:authenticationSchemeHandler" minOccurs="1"
                         maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="callbackHandler" type="tns:callbackHandler"/>
</xsd:schema>

=== clescot/jguard/jguard-ext/src/test/resources/jGuardFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ jGuard is a security framework based on top of jaas (java authentication and authorization security).
  ~ it is written for web applications, to resolve simply, access control problems.
  ~ version $Name$
  ~ http://sourceforge.net/projects/jguard/
  ~
  ~ Copyright (C) 2004-2009  Charles GAY
  ~
  ~ This library is free software; you can redistribute it and/or
  ~ modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either
  ~ version 2.1 of the License, or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public
  ~ License along with this library; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
  ~
  ~
  ~ jGuard project home page:
  ~ http://sourceforge.net/projects/jguard/
  -->

<callbackHandler xmlns="http://jguard.sourceforge.net/xsd/jGuardFilter_2.0.0.xsd"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
                 xs:schemaLocation="http://jguard.sourceforge.net/xsd/jGuardFilter_2.0.0.xsd jGuardFilter_2.0.0.xsd">
    <authenticationSchemeHandler
            className="net.sf.jguard.core.authentication.schemes.DummyAuthenticationSchemeHandler">
        <!-- Uri to access to the authentication form -->
        <parameter key="logonURI" value="/Logon.do"/>
        <!--  uri to be authenticated. The action property of the authentication form MUST NOT be set to j_security_check. -->
        <parameter key="logonProcessURI" value="/LogonProcess.do*"/>
        <!-- uri to to be unauthenticated -->
        <parameter key="logoffURI" value="/Logoff.do*"/>
        <parameter key="loginField" value="login"/>
        <!-- Parameter's name of the form's field which holds the password. All values are accepted except j_password. -->
        <parameter key="passwordField" value="password"/>
        <parameter key="goToLastAccessDeniedUriOnSuccess" value="true"/>
        <!-- Uri when the user authentication failed. -->
        <parameter key="authenticationFailedURI" value="/AuthenticationFailed.do*"/>
        <!-- Index uri of your web application. -->
        <parameter key="authenticationSucceedURI" value="/index.jsp"/>
        <!-- uri when access to a resource is denied -->
        <parameter key="accessDeniedURI" value="/AccessDenied.do*"/>
    </authenticationSchemeHandler>
</callbackHandler>

=== clescot/jguard/jguard-jee-extras/src/test/resources/jGuardFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<callbackHandler xmlns="http://jguard.sourceforge.net/xsd/jGuardFilter_2.0.0.xsd"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
                 xs:schemaLocation="http://jguard.sourceforge.net/xsd/jGuardFilter_2.0.0.xsd jGuardFilter_2.0.0.xsd">
    <authenticationSchemeHandler className="net.sf.jguard.jsf.authentication.schemes.JSFLoginPasswordFormSchemeHandler">
        <!-- Uri to access to the authentication form -->
        <parameter key="logonURI" value="/jsp/logon.jsp"/>
        <!--  uri to be authenticated. The action property of the authentication form MUST NOT be set to j_security_check. -->
        <parameter key="logonProcessURI" value="/logonProcess.jsp"/>
        <!-- uri to to be unauthenticated -->
        <parameter key="logoffURI" value="/jsp/logoff.jsp"/>
        <parameter key="loginField" value="login"/>
        <!-- Parameter's name of the form's field which holds the password. All values are accepted except j_password. -->
        <parameter key="passwordField" value="password"/>
        <parameter key="goToLastAccessDeniedUriOnSuccess" value="true"/>
        <!-- Uri when the user authentication failed. -->
        <parameter key="authenticationFailedURI" value="authenticationFailed"/>
        <!-- Index uri of your web application. -->
        <parameter key="authenticationSucceedURI" value="/welcome.jsp"/>
        <!-- uri when access to a ressource is denied -->
        <parameter key="accessDeniedURI" value="accessDenied"/>
    </authenticationSchemeHandler>
    <authenticationSchemeHandler className="net.sf.jguard.jsf.authentication.callbacks.JSFAuditSchemeHandler"/>
</callbackHandler>

        <!--<registerURI>/jsp/registration.jsp</registerURI>
        <registerProcessURI>/RegistrationProcess.jsp</registerProcessURI>-->
